stages:
  - pdf

services:
  - docker:dind

make-pdf:
  stage: pdf
  image: docker:latest
  before_script:
    - apk --no-cache add git just
  script:
    - just build
    - just run
  artifacts:
    paths:
      - resume.pdf
    expire_in: 1 day
